"""Structurizr DSL generator for C4 diagrams."""

from __future__ import annotations

from pathlib import Path

from archpipe.generators.base import BaseGenerator
from archpipe.models.ir_schema import ElementType, IRModel
from archpipe.models.profile import DEFAULT_PROFILE, NotationProfile


def _dsl_id(raw_id: str) -> str:
    sanitized = []
    for char in raw_id:
        if char.isascii() and (char.isalnum() or char in {"_", "-"}):
            sanitized.append(char)
        else:
            sanitized.append("_")

    value = "".join(sanitized).replace("-", "_").strip("_")
    while "__" in value:
        value = value.replace("__", "_")

    if not value:
        value = "id"
    if value[0].isdigit():
        value = f"id_{value}"
    return value


def _compact_label(value: str) -> str:
    normalized = " ".join(value.split())
    if not normalized:
        return "link"
    return _wrap_label(normalized, 28)


def _wrap_label(value: str, max_chars: int) -> str:
    words = value.split()
    if not words:
        return value

    lines: list[str] = []
    current = words[0]
    for word in words[1:]:
        if len(current) + len(word) + 1 <= max_chars:
            current = f"{current} {word}"
        else:
            lines.append(current)
            current = word
    lines.append(current)
    return "\\n".join(lines)


class C4Generator(BaseGenerator):
    """Generate Structurizr DSL workspace and styles."""

    name = "c4"

    def __init__(self, profile: NotationProfile | None = None) -> None:
        self.profile = profile or DEFAULT_PROFILE

    def generate(self, model: IRModel, output_dir: Path, force: bool = False) -> list[Path]:
        c4_dir = output_dir / "diagrams" / "c4"
        workspace_path = c4_dir / "workspace.dsl"
        styles_path = c4_dir / "styles.dsl"

        workspace_content = self._render_workspace(model)
        styles_content = self._render_styles()

        self._write_file(workspace_path, workspace_content, force)
        self._write_file(styles_path, styles_content, force)

        return [workspace_path, styles_path]

    def _render_workspace(self, model: IRModel) -> str:
        system_id = _dsl_id(model.system.name.lower().replace(" ", "_"))
        lines: list[str] = [
            f'workspace "{model.metadata.title}" "Generated by archpipe-cli" {{',
            "    model {",
            "",
        ]

        id_map: dict[str, str] = {}
        self._append_external_systems(lines, model, id_map)
        lines.append(
            (
                f'        {system_id} = softwareSystem "{model.system.name}" '
                f'"{model.system.description}" {{'
            ),
        )
        lines.append("")
        self._append_containers_and_components(lines, model, id_map)
        self._append_relationships(lines, model, id_map)
        self._append_views(lines, model, system_id)
        return "\n".join(lines)

    def _append_external_systems(
        self,
        lines: list[str],
        model: IRModel,
        id_map: dict[str, str],
    ) -> None:
        for ext in sorted(model.external_systems, key=lambda item: item.id):
            ext_var = _dsl_id(ext.id)
            id_map[ext.id] = ext_var
            description = ext.description or "External system"
            lines.append(
                f'        {ext_var} = softwareSystem "{ext.name}" "{description}" "External"',
            )

    def _append_containers_and_components(
        self,
        lines: list[str],
        model: IRModel,
        id_map: dict[str, str],
    ) -> None:
        for container in sorted(model.containers, key=lambda item: item.id):
            container_var = _dsl_id(container.id)
            id_map[container.id] = container_var
            tag = container.type.value.capitalize()
            lines.append(
                "            "
                f'{container_var} = container "{container.name}" '
                f'"{container.description}" "{container.technology}" "{tag}"',
            )

            for component in sorted(container.components, key=lambda item: item.id):
                component_var = f"{container_var}_{_dsl_id(component.id)}"
                id_map[component.id] = component_var
                lines.append(
                    "            "
                    f'{component_var} = component "{component.name}" '
                    f'"{component.description}" "{component.technology}" "Component"',
                )

        lines.append("        }")
        lines.append("")

    def _append_relationships(
        self,
        lines: list[str],
        model: IRModel,
        id_map: dict[str, str],
    ) -> None:
        for rel in sorted(
            model.relationships,
            key=lambda item: (item.from_id, item.to_id, item.description, item.protocol or ""),
        ):
            src = id_map.get(rel.from_id, _dsl_id(rel.from_id))
            dst = id_map.get(rel.to_id, _dsl_id(rel.to_id))
            caption = _compact_label(rel.description)
            lines.append(
                f'        {src} -> {dst} "{caption}"',
            )

        for integration in sorted(
            model.integrations,
            key=lambda item: (item.from_id, item.to_id, item.description or "", item.protocol or ""),
        ):
            src = id_map.get(integration.from_id, _dsl_id(integration.from_id))
            dst = id_map.get(integration.to_id, _dsl_id(integration.to_id))
            description = integration.description or "Integration"
            caption = _compact_label(description)
            lines.append(f'        {src} -> {dst} "{caption}"')

    def _append_views(
        self,
        lines: list[str],
        model: IRModel,
        system_id: str,
    ) -> None:
        lines.extend([
            "    }",
            "",
            "    views {",
            f"        systemContext {system_id} {{",
            "            include *",
            f"            autoLayout {self.profile.c4.auto_layout}",
            "        }",
            "",
            f"        container {system_id} {{",
            "            include *",
            f"            autoLayout {self.profile.c4.auto_layout}",
            "        }",
            "",
        ])

        for container in model.containers:
            if not container.components:
                continue
            container_var = _dsl_id(container.id)
            lines.extend([
                f"        component {container_var} {{",
                "            include *",
                f"            autoLayout {self.profile.c4.auto_layout}",
                "        }",
                "",
            ])

        lines.extend([
            "        styles {",
            "            relationship \"Relationship\" {",
            "                fontSize 11",
            "            }",
            "            element \"Container\" {",
                f"                background {self.profile.c4.internal_bg}",
                f"                color {self.profile.c4.text_color}",
                f"                stroke {self.profile.c4.stroke_color}",
                "                fontSize 14",
            "            }",
            "            element \"Database\" {",
                "                shape cylinder",
                f"                background {self.profile.c4.internal_bg}",
                f"                color {self.profile.c4.text_color}",
                f"                stroke {self.profile.c4.stroke_color}",
                "                fontSize 14",
            "            }",
            "            element \"Queue\" {",
                "                shape pipe",
                f"                background {self.profile.c4.internal_bg}",
                f"                color {self.profile.c4.text_color}",
                f"                stroke {self.profile.c4.stroke_color}",
                "                fontSize 14",
            "            }",
            "            element \"Cache\" {",
                f"                background {self.profile.c4.internal_bg}",
                f"                color {self.profile.c4.text_color}",
                f"                stroke {self.profile.c4.stroke_color}",
                "                fontSize 14",
            "            }",
            "            element \"Component\" {",
                f"                background {self.profile.c4.internal_bg}",
                f"                color {self.profile.c4.text_color}",
                f"                stroke {self.profile.c4.stroke_color}",
                "                fontSize 14",
            "            }",
            "            element \"External\" {",
                f"                background {self.profile.c4.external_bg}",
                f"                color {self.profile.c4.text_color}",
                f"                stroke {self.profile.c4.stroke_color}",
                "                fontSize 14",
                "                border dashed",
            "            }",
            "        }",
            "    }",
            "}",
            "",
        ])

    def _render_styles(self) -> str:
        return "\n".join(
            [
                "styles {",
                "    relationship \"Relationship\" {",
                "        fontSize 11",
                "    }",
                "    element \"Container\" {",
                f"        background {self.profile.c4.internal_bg}",
                f"        color {self.profile.c4.text_color}",
                f"        stroke {self.profile.c4.stroke_color}",
                "        fontSize 14",
                "    }",
                "    element \"Database\" {",
                "        shape cylinder",
                f"        background {self.profile.c4.internal_bg}",
                f"        color {self.profile.c4.text_color}",
                f"        stroke {self.profile.c4.stroke_color}",
                "        fontSize 14",
                "    }",
                "    element \"Queue\" {",
                "        shape pipe",
                f"        background {self.profile.c4.internal_bg}",
                f"        color {self.profile.c4.text_color}",
                f"        stroke {self.profile.c4.stroke_color}",
                "        fontSize 14",
                "    }",
                "    element \"Cache\" {",
                f"        background {self.profile.c4.internal_bg}",
                f"        color {self.profile.c4.text_color}",
                f"        stroke {self.profile.c4.stroke_color}",
                "        fontSize 14",
                "    }",
                "    element \"Component\" {",
                f"        background {self.profile.c4.internal_bg}",
                f"        color {self.profile.c4.text_color}",
                f"        stroke {self.profile.c4.stroke_color}",
                "        fontSize 14",
                "    }",
                "    element \"External\" {",
                f"        background {self.profile.c4.external_bg}",
                f"        color {self.profile.c4.text_color}",
                f"        stroke {self.profile.c4.stroke_color}",
                "        fontSize 14",
                "        border dashed",
                "    }",
                "}",
                "",
            ],
        )
